version: '2.1'
networks:
  log-arch:
    driver: bridge
    ipam:
      config:
        - subnet: 172.8.0.0/22

services:
  nifi:
    image: apache/nifi:latest
    container_name: nifi
    restart: always
    environment:
      - NIFI_WEB_HTTP_PORT=9090
    volumes:
  #     - ./nifi/conf:/opt/nifi/nifi-current/conf
  #     - ./nifi/content:/opt/nifi/nifi-current/content_repository
  #     - ./nifi/db:/opt/nifi/nifi-current/database_repository
  #     - ./nifi/flowfile:/opt/nifi/nifi-current/flowfile_repository
  #     - ./nifi/state:/opt/nifi/nifi-current/state
  #     - ./nifi/logs:/opt/nifi/nifi-current/logs
      - ./nifi/data_store:/opt/nifi/nifi-current/data_store
    ports:
      - "9090:9090"
    networks:
      - log-arch

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    restart: unless-stopped

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
#      - KAFKA_ADVERTISED_HOST_NAME=localhost
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENERS=INSIDE_LISTENER://0.0.0.0:29092,OUTSIDE_LISTENER://0.0.0.0:9092
      - KAFKA_ADVERTISED_LISTENERS=INSIDE_LISTENER://kafka:29092,OUTSIDE_LISTENER://localhost:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INSIDE_LISTENER:PLAINTEXT,OUTSIDE_LISTENER:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=INSIDE_LISTENER
      - KAFKA_ADVERTISED_HOST_NAME=localhost
      - KAFKA_CREATE_TOPICS=log_flow:1:1
    restart: unless-stopped
    depends_on:
      - zookeeper
    networks:
      - log-arch

  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    hostname: namenode
    restart: unless-stopped
    ports:
      - "9870:9870"
      - "8020:8020"
    volumes:
      - ./hdfs/namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
    networks:
      - log-arch

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    hostname: datanode
    restart: unless-stopped
    volumes:
      - ./hdfs/dataode:/hadoop/dfs/data
    environment:
      - SERVICE_PRECONDITION=namenode:9870
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
    ports:
      - "50075:50075"
      - "50010:50010"
      - "50020:50020"
    depends_on:
      - namenode
    networks:
      - log-arch

  spark-master:
      image: bde2020/spark-master:3.3.0-hadoop3.3
      container_name: spark-master
      hostname: spark-master
      healthcheck:
        interval: 5s
        retries: 100
      ports:
        - "8080:8080"
        - "7077:7077"
        - "7040:7040"
        - "7041:7041"
      environment:
        - INIT_DAEMON_STEP=false
        - SPARK_DRIVER_HOST=192.168.1.5
      volumes:
        - ./spark-job:/opt/spark_store
      networks:
        - log-arch

  spark-worker-1:
    image: bde2020/spark-worker:3.3.0-hadoop3.3
    container_name: spark-worker-1
    hostname: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
#    volumes:
#      - ./data/spark/:/opt/spark-data
    networks:
      - log-arch