services:
  nifi:
    image: apache/nifi:latest
    restart: always
    environment:
      - NIFI_WEB_HTTP_PORT=9090
    volumes:
#      - ./nifi/conf:/opt/nifi/nifi-current/conf
#      - ./nifi/content:/opt/nifi/nifi-current/content_repository
#      - ./nifi/db:/opt/nifi/nifi-current/database_repository
#      - ./nifi/flowfile:/opt/nifi/nifi-current/flowfile_repository
#      - ./nifi/state:/opt/nifi/nifi-current/state
#      - ./nifi/logs:/opt/nifi/nifi-current/logs
      - ./nifi/data_store:/opt/nifi/nifi-current/data_store
    ports:
      - 9090:9090
